version: '3.8'

services:
  postgres:
    image: 'postgres:15-alpine'
    container_name: postgres-db
    expose:
      - 5432
    ports:
      - '5432:5432'
    env_file:
      - .env
    restart: always
    networks:
      - hulk

  api:
    container_name: api-app
    depends_on:
      - postgres
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - '4000:4000'
    networks:
      - hulk
  front:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: front-app
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - api
    networks:
      - hulk
volumes:
  postgres:
    driver: local
networks:
  hulk:
    external:
      name: hulknet
