version: '3.8'

services:
  postgres:
    image: 'postgres:15-alpine'
    container_name: postgres-db
    expose:
      - 5432
    ports:
      - '5432:5432'
    env_file:
      - .env
    restart: always
  api:
    container_name: api
    restart: always
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    ports:
      - '4000:4000'
  front:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    container_name: front
    ports:
      - '5000:80'
      - '443:443'
    depends_on:
      - api
volumes:
  postgres:
    driver: local
    # networks:
    #   - hulk
# networks:
#   hulk:
#     external:
#       name: hulknet
