version: '3.8'

services:
  postgres:
    image: 'postgres:15-alpine'
    container_name: postgres-db
    expose:
      - 5432
    ports:
      - '5432:5432'
    env_file:
      - .env
volumes:
  postgres:
    driver: local
    # networks:
    #   - hulk
# networks:
#   hulk:
#     external:
#       name: hulknet
